# Generated by Django 4.2.16 on 2026-06-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
